### ISSUE TITLE
Use Javascript Proxies to reduce amount of source code

### ISSUE THREAD

**Issue by exouler** [Swizz/hyperapp-html#17]
Javascript [Proxies are useful and can reduce the amount of source code](https://flems.io/#0=N4IgZglgNgpgziAXAbVAOwIYFsZJAOgAsAXLKEAGhAGMB7NYmBvEAXwvW10QICsEqdBk2J4hcYgAJghCpIwAHBa0kBeSYQCeCmACdFCgDppjYAK5pqxCPUkA3NLQAmMABSYcASmnHJk3TDEZrpokuaW1rauGMTEuhAARmaMcHLUhNBOAWjewL5+-oHBocTaMLRg8rHxSSlqquqGILQJvDBWTZIAZF2SAIQAgrr6mvgQcEMj0dWJyfCe+QWSAPwa7lxyMXGzKWkZUFlMC6FLkohrHjBywOxV27Xz+azGzyaW9BKSMLA4DABiGCstF0mjUkjQMAA7pIAAq6WgAD00rhu13yAHNAudwlYbGhXAB9OTEDDogByXFyi0KQRCYQsuKiWxqc1SknSmWyVJOSwCtNCDmcbhJ5Mp03urL2nKO1NeflerGOkmM4ikwEkTggdjkhAAjHJasRbCp1N8YL9iACgSDjCqPlIJDEYGC8ic6BZiOcAAwvW3vNCfQGRAMu-JOWiQtDnOwYKBmZ2qAB8kkdjDUyZR7NoHvOqZg+HdDEkAFp7LH45JFRR8mYFNHywnk3n05JM4XPSmSYwC9miwBqMtx52K31vVX2CBQsGuPObRkB7xJ5UnTV2VzIal6mdd-PtzzVnmSQ30VzSST0ahQCDUADW51ci+TQbxcHw4cjrl13luTWLTX31LHviZ4Xlet73o+8jzq+taft+chNH2-6+AAukqxgGNuTpzsGbJ2JOkJyOG1BmBa+AJM4mieJQIBwGa0F4AATF6iBemwHAgJceAFnAAg0PQjDMDwbAoVQV5oDeCAoJwOB4FoOj6EoNHBOQPAkMQChwIgAD02kWAoN7oj2WDafJegGAAArq+CMfgACc2mahIpllIpCj4PwNGlDoeBwNQ8QKKIrAoawQA
).

**Comment by jorgebucaran** [comment]
👋 Hi! @exouler.

I'm unclear what's being asked here. Is this a question? Is this a commentary? Is this a feature request?

If you just want to chat freely, [join us on Slack](https://hyperappjs.herokuapp.com/), otherwise post an actual bug-report or issue you had with the project.

Cheers!
