### ISSUE TITLE
Add support for head tags? (meta, title, link, etc)

### ISSUE THREAD

**Issue by whaaaley** [Swizz/hyperapp-html#18]
The title says it all. I want to use this along side hyperapp render, but all my head tags need to use `h` instead of this because they simply don't exist. Thoughts?

**Comment by jorgebucaran** [comment]
@whaaaley Hyperapp's virtual DOM was not meant to be used to create any of those tags. Not to say you can't create some of them with Hyperapp, but you may experience unexpected results.

**Comment by whaaaley** [comment]
That's true. My use case extends beyond hyperapp though. Is this project's scope limited to hyperapp itself or can it be extended for server-side use as well?

**Comment by jorgebucaran** [comment]
@whaaaley Ultimately up to @Swizz. It's currently limited to Hyperapp.

https://github.com/Swizz/hyperapp-html/blob/4c6913c4f38e7ac2b3036b9add92e0c5475be918/src/html.js#L1

**Comment by whaaaley** [comment]
Well, it's not _exactly_ limited. This snippet is how I pass my view to hyperapp-render.

```js
import { readFileSync } from 'fs'
import { renderToString } from '@hyperapp/render/browser'
import { state } from './logic'
import Stub from './views/Stub'

const view = () => {
  const css = readFileSync('./public/app.css', 'utf-8')
  const js = readFileSync('./public/app.js', 'utf-8')
  return Stub({ css, js })
}

process.stdout.write('<!DOCTYPE html>' + renderToString(view, state))
```

So all I would really need is a few more tags tossed in the var list in this project. So I hope that's within reason 🙏 .

**Comment by jorgebucaran** [comment]
@whaaaley I mean Hyperapp as a whole. This package only works with `hyperapp.h`. I believe `hyperapp-render` does too. Therefore you can use them together. I see your point now, though. 😄

**Comment by whaaaley** [comment]
Maybe keep head elements in a separate files so they have to be imported separately? This would work great for me, as my `stub.js` _only_ needs head elements and nothing else. A helmet project would be useful too, but I don't think it would solve this "issue" I'm having for ssr/pre-rendered pages.

**Comment by lukejacksonn** [comment]
Just curious.. why is it not encouraged to use VDOM to control the head of your document? This is along the same thread of https://github.com/jorgebucaran/hyperapp/issues/780

**Comment by jorgebucaran** [comment]
@lukejacksonn Hyperapp has no built-in checking for tags. It assumes everything is inside the `body`. Have you tried creating `title`, `base`, `meta`, `link`, `script`, `noscript`, and `style` tags? Those usually go inside the `head`. I am not sure that Hyperapp will correctly create all of them.

**Comment by lukejacksonn** [comment]
I have, they work as expected in my experiments – same with react!

**Comment by jorgebucaran** [comment]
I think I had misunderstood what React Helmet was for. This helped cleared some doubts for me: https://stackoverflow.com/questions/52690820/what-is-the-purpose-of-react-helmet.

**Comment by lukejacksonn** [comment]
It dawned on me that `react-helmet` is just doing a diff similar to that of `patch`. So why not just let the vdom handle the `heads` like any other element? I am not suggesting it is normal (or better or worse in any way) but I am yet to discover a very good reason _not_ to do this if you have complete control over your app.

**Comment by jorgebucaran** [comment]
I haven't looked into it yet, but according to that link/answer React Helmet allows multiple components to update the head.

**Comment by jorgebucaran** [comment]
Same. I'm not opposed to this idea by the way. 

@whaaaley Send a PR?

**Comment by whaaaley** [comment]
Okay dokey :D

**Comment by whaaaley** [comment]
I'm a bit late but... #20
