### ISSUE TITLE
Does size matter?

### ISSUE THREAD

**Issue by fidian** [Swizz/hyperapp-html#19]
I noticed that there's a lot of redundant code in the minified version, which is because you're exporting a lot of similar functions. However, the minified code is wrapped in UMD, so making those exports using the templating that you're doing isn't really necessary.

I've got a set of changes that moves `vars.json` into the JavaScript and builds a set of functions while iterating over an array. The size difference is noticeable.

    html.js original: 9590 bytes
    html.js modified: 1998 bytes, about 80% smaller

This also implements that factory function as discussed in #4. I didn't see bloat. The drawback is that people would have to change how they use the library.

    // old
    import { app } from "hyperapp"; // not really necessary to import h
    import { div, h1, button } from "@hyperapp/html"

    // modified
    import { app, h } from "hyperapp";
    import { hyperappHtml } from "@hyperapp/html"
    { div, h1, button } = hyperappHtml(h);

This is not a pull request because I wanted to see the discussion. This approach does two things:

1. The minified code shows significant improvement in size.
2. Exporting of a factory function so this is not bound tightly to hyperapp.

**Comment by jorgebucaran** [comment]
@fidian Thank you. This package has moved to [@hyperapp/html](https://github.com/jorgebucaran/hyperapp/tree/master/pkg/html). I've implemented something similar to what you've said, but the usage is essentially the same.

Cheers! 👋
